### ISSUE TITLE
Menu hamburger selector isn't left justified when the window is fitted to just half of a screen

### ISSUE THREAD

**Issue by nategoethel** [klmui/Course-Quad#4]
If you open Course Quad and then snap the window (Windows key + left arrow or right arrow), the hamburger button to open the menu isn't justified to the left like the X button.
![Hamburger Justify Issue](https://user-images.githubusercontent.com/44580393/85488999-ed585d80-b594-11ea-859e-bda1d8c92629.PNG)

**Comment by klmui** [comment]
I'll get on that soon! Thanks for letting me know. I thought I had accounted for responsiveness earlier, but it's not working now.

**Comment by klmui** [comment]
I just fixed it! I'm about to merge my branch! I forgot to change my code to account for the size of your window and not the size of your screen. I tested it on phone screens too, but it's not optimized for screens smaller than a phone screen though.
